In [29]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [30]:
df = pd.read_csv('../data/telecom_churn.csv')
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [31]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,437.182418,8.099010,179.775098,100.435644,30.562307,200.980348,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856
std,39.822106,42.371290,13.688365,54.467389,20.069084,9.259435,50.713844,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.430000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.400000,114.000000,36.790000,235.300000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   str
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   str
 4   Voice mail plan         3333 non-null   str
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3333 non-null   float64
 7   Total day calls         3333 non-null   int64
 8   Total day charge        3333 non-null   float64
 9   Total eve minutes       3333 non-null   float64
 10  Total eve calls         3333 non-null   int64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3333 non-null   int64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3333 non-null   float64
 18  Customer service calls  3333 non-null   int64
 19  Churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), str(3)
memory usage: 518.9 KB

In [33]:
df.drop(['State', 'Voice mail plan'], axis=1, inplace=True)

In [34]:
df['International plan'] = df['International plan'].map({'Yes': 1, 'No': 0}, inplace=True)

In [35]:
# Целевой признак
y = df['Churn'].astype('int')

In [36]:
# Матрица X
X = df.drop('Churn', axis=1)

In [37]:
# Проверка размерностей
X.shape, y.shape

((3333, 17), (3333,))

In [44]:
from sklearn.model_selection import train_test_split, cross_val_score
import numpy as np

In [39]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=42)

In [40]:
X_train.shape, X_valid.shape

((2333, 17), (1000, 17))

In [41]:
first_tree = DecisionTreeClassifier(random_state=42)

In [46]:
np.mean(cross_val_score(first_tree, X_train, y_train, cv=5))

np.float64(0.9018545919070682)

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [59]:
first_knn = KNeighborsClassifier()

In [60]:
np.mean(cross_val_score(first_knn, X_train, y_train, cv=5))

np.float64(0.8636920899541407)

In [61]:
### max_depth для дерева
from sklearn.model_selection import GridSearchCV

In [71]:
# Tree
tree_params = {'max_depth': np.arange(1, 11), 'max_features': [0.5, 0.7, 1]}
tree_grid = GridSearchCV(first_tree, tree_params, cv=5, n_jobs=-1)

In [72]:
tree_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
                         'max_features': [0.5, 0.7, 1]})

In [73]:
tree_grid.best_score_, tree_grid.best_params_

(np.float64(0.9378527906185955),
 {'max_depth': np.int64(6), 'max_features': 0.5})

In [79]:
# KNN
knn_params = {'n_neighbors': range(5, 30, 5)}
knn_grid = GridSearchCV(first_knn, knn_params, cv=5, n_jobs=-1)

In [80]:
knn_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(5, 30, 5)})

In [81]:
knn_grid.best_score_, knn_grid.best_params_

(np.float64(0.8688349523485677), {'n_neighbors': 15})

In [82]:
tree_grid.best_estimator_

DecisionTreeClassifier(max_depth=np.int64(6), max_features=0.5, random_state=42)

In [83]:
tree_valid_pred = tree_grid.predict(X_valid)

In [85]:
from sklearn.metrics import accuracy_score

In [88]:
accuracy_score(tree_valid_pred, y_valid)

0.942

In [91]:
from sklearn.tree import export_graphviz

In [93]:
export_graphviz(tree_grid.best_estimator_, out_file='telecom_tree.dot', feature_names=X.columns, filled=True)

In [99]:
!dot -Tpng telecom_tree.dot -o telecom_tree.png

<img src='telecom_tree.png'>