In [96]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [97]:
df = pd.read_csv('../data/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [98]:
new_df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
new_df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [99]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(2)
memory usage: 60.9 KB

In [100]:
new_df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [101]:
new_df['Sex'] = new_df['Sex'].map({'male':1, 'female':0})
new_df['Embarked'] = new_df['Embarked'].map({'S':1, 'C':2, 'Q':3})

In [102]:
new_df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500       1.0
1         1       1    0  38.0      1      0  71.2833       2.0
2         1       3    0  26.0      0      0   7.9250       1.0
3         1       1    0  35.0      1      0  53.1000       1.0
4         0       3    1  35.0      0      0   8.0500       1.0

In [103]:
new_df = new_df.dropna()

In [104]:
y = new_df['Survived']
X = new_df.drop(['Survived'], axis=1)

In [105]:
y.shape, X.shape

((712,), (712, 7))

In [106]:
from sklearn.model_selection import train_test_split, cross_val_score
import numpy as np

In [107]:
X_train, X_holdout, y_train, y_holdout = train_test_split(X, y, test_size=0.3, random_state=42)

In [108]:
X_train.shape, X_holdout.shape

((498, 7), (214, 7))

In [109]:
tree = DecisionTreeClassifier(random_state=42)

In [110]:
np.mean(cross_val_score(tree, X_train, y_train, cv=5))

np.float64(0.7431111111111111)

In [111]:
from sklearn.neighbors import KNeighborsClassifier

In [112]:
Knn = KNeighborsClassifier()

In [113]:
np.mean(cross_val_score(Knn, X_train, y_train, cv=5))

np.float64(0.696949494949495)

In [114]:
# Найдем лучшие параметры
from sklearn.model_selection import GridSearchCV

In [115]:
tree_params = {'max_depth': np.arange(1, 15), 'max_features': [0.2, 0.4, 0.6, 0.8, 1]}
tree_grid = GridSearchCV(tree, tree_params, cv=5, n_jobs=-1)

In [116]:
tree_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                         'max_features': [0.2, 0.4, 0.6, 0.8, 1]})

In [117]:
tree_grid.best_params_, tree_grid.best_score_

({'max_depth': np.int64(4), 'max_features': 0.8},
 np.float64(0.7991111111111111))

In [118]:
knn_params = {'n_neighbors': range(1, 15)}
knn_grid = GridSearchCV(Knn, knn_params, cv=5, n_jobs=-1)

In [119]:
knn_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(1, 15)})

In [120]:
knn_grid.best_params_, knn_grid.best_score_

({'n_neighbors': 6}, np.float64(0.721030303030303))

In [128]:
tree_prediction = tree_grid.predict(X_holdout)
knn_prediction = knn_grid.predict(X_holdout)

In [129]:
from sklearn.metrics import accuracy_score

In [130]:
accuracy_score(y_holdout, tree_prediction)

0.719626168224299

In [131]:
accuracy_score(y_holdout, knn_prediction)

0.616822429906542