In [54]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [55]:
df = pd.read_csv('../data/bank-full.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 8.1 MB

In [57]:
df['job'].value_counts()

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [58]:
df['job'] = df['job'].map({'blue-collar': 1, 'management':2, 'technician':3, 'admin.':4, 'services':5, 'retired':6, 'self-employed':7, 'entrepreneur':8, 'unemployed':9, 'housemaid':10, 'student':11, 'unknown':0})
df['marital'] = df['marital'].map({'married': 1, 'single': 2, 'divorced': 0})
df['education'] = df['education'].map({'tertiary': 1, 'secondary': 2, 'primary': 3, 'unknown': 0})
df['housing'] = df['housing'].map({'yes': 1, 'no': 0})
df['loan'] = df['loan'].map({'yes': 1, 'no': 0})
df['contact'] = df['contact'].map({'cellular': 1, 'telephone': 2, 'unknown': 0})
df['y'] = df['y'].map({'yes': 1, 'no': 0})

In [59]:
df = df.drop(['default', 'day', 'month', 'poutcome', 'duration', 'campaign', 'pdays', 'previous'], axis=1)

In [60]:
df.head()

   age  job  marital  education  balance  housing  loan  contact  y
0   58    2        1          1     2143        1     0        0  0
1   44    3        2          2       29        1     0        0  0
2   33    8        1          2        2        1     1        0  0
3   47    1        1          0     1506        1     0        0  0
4   33    0        2          0        1        0     0        0  0

In [61]:
df = df.dropna()

In [62]:
y = df['y']
X = df.drop('y', axis=1)

In [63]:
X.shape, y.shape

((45211, 8), (45211,))