In [118]:
import pickle
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook
from scipy.sparse import csr_matrix, hstack
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [119]:
train_df = pd.read_csv('../data/train_sessions.csv', index_col='session_id')
test_df = pd.read_csv('../data/test_sessions.csv', index_col='session_id')

In [120]:
times = ['time%s' % i for i in range(1, 11)]
train_df[times] = train_df[times].apply(pd.to_datetime)
test_df[times] = test_df[times].apply(pd.to_datetime)

In [121]:
train_df = train_df.sort_values(by='time1')
train_df.head()

,site1,time1,site2,time2,site3,time3,site4,time4,site5,time5,...,time6,site7,time7,site8,time8,site9,time9,site10,time10,target
session_id,,,,,,,,,,,,,,,,,,,,,
21669,56,2013-01-12 08:05:57,55.0,2013-01-12 08:05:57,NaN,NaT,NaN,NaT,NaN,NaT,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,0
54843,56,2013-01-12 08:37:23,55.0,2013-01-12 08:37:23,56.0,2013-01-12 09:07:07,55.0,2013-01-12 09:07:09,NaN,NaT,...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,0
77292,946,2013-01-12 08:50:13,946.0,2013-01-12 08:50:14,951.0,2013-01-12 08:50:15,946.0,2013-01-12 08:50:15,946.0,2013-01-12 08:50:16,...,2013-01-12 08:50:16,948.0,2013-01-12 08:50:16,784.0,2013-01-12 08:50:16,949.0,2013-01-12 08:50:17,946.0,2013-01-12 08:50:17,0
114021,945,2013-01-12 08:50:17,948.0,2013-01-12 08:50:17,949.0,2013-01-12 08:50:18,948.0,2013-01-12 08:50:18,945.0,2013-01-12 08:50:18,...,2013-01-12 08:50:18,947.0,2013-01-12 08:50:19,945.0,2013-01-12 08:50:19,946.0,2013-01-12 08:50:19,946.0,2013-01-12 08:50:20,0
146670,947,2013-01-12 08:50:20,950.0,2013-01-12 08:50:20,948.0,2013-01-12 08:50:20,947.0,2013-01-12 08:50:21,950.0,2013-01-12 08:50:21,...,2013-01-12 08:50:21,946.0,2013-01-12 08:50:21,951.0,2013-01-12 08:50:22,946.0,2013-01-12 08:50:22,947.0,2013-01-12 08:50:22,0

In [122]:
sites = ['site%s' % i for i in range(1, 11)]
train_df[sites] = train_df[sites].fillna(0).astype('int')
test_df[sites] = test_df[sites].fillna(0).astype('int')

In [123]:
with open(r'../data/site_dic.pkl', 'rb') as input_file:
    site_dic = pickle.load(input_file)

sites_dict_df = pd.DataFrame(list(site_dic.keys()),
                             index=list(site_dic.values()),
                             columns=['site'])
sites_dict_df.head()

                                     site
25075              www.abmecatronique.com
13997                     groups.live.com
42436  majeureliguefootball.wordpress.com
30911           cdt46.media.tourinsoft.eu
8104                  www.hdwallpapers.eu

In [124]:
y_train = train_df['target']
full_df = pd.concat([train_df.drop('target', axis=1), test_df])
idx_split = train_df.shape[0]

In [125]:
sites = ['site%d' % i for i in range(1, 10)]
full_sites = full_df[sites]
full_sites.head()

            site1  site2  site3  site4  site5  site6  site7  site8  site9
session_id
21669          56     55      0      0      0      0      0      0      0
54843          56     55     56     55      0      0      0      0      0
77292         946    946    951    946    946    945    948    784    949
114021        945    948    949    948    945    946    947    945    946
146670        947    950    948    947    950    952    946    951    946

In [126]:
n_rows, n_cols = full_sites.shape
sites_flatten = full_sites.values.flatten()

full_sites_sparse = csr_matrix(
    (
        np.ones(len(sites_flatten), dtype=np.int8),
        sites_flatten,
        np.arange(0, (n_rows + 1) * n_cols, n_cols),
    )
)[:, 1:]

In [127]:
X_train_sparse = full_sites_sparse[:idx_split]
X_test_sparse = full_sites_sparse[idx_split:]

In [128]:
X_train_sparse.shape, X_test_sparse.shape

((253561, 48371), (82797, 48371))

In [129]:
def get_auc_1r_valid(X, y, C=1.0, ratio=0.9, seed=17):
    train_len = int(ratio * X.shape[0])
    X_train = X[:train_len, :]
    X_test = X[train_len:, :]
    y_train = y[:train_len]
    y_test = y[train_len:]

    logit = LogisticRegression(C=C, random_state=seed)

    logit.fit(X_train, y_train)
    valid_pred = logit.predict_proba(X_test)[:, 1]

    return roc_auc_score(y_test, valid_pred)

In [130]:
get_auc_1r_valid(X_train_sparse, y_train)

0.9145798840434793

In [131]:
%%time
logit = LogisticRegression(random_state=17)
logit.fit(X_train_sparse, y_train)

CPU times: user 749 ms, sys: 79.9 ms, total: 829 ms
Wall time: 660 ms

LogisticRegression(random_state=17)

In [132]:
test_pred = logit.predict_proba(X_test_sparse)[:, 1]

In [133]:
# Файл для посылки на kaggle
pd.Series(test_pred, index=range(1, test_pred.shape[0] + 1), name='target').to_csv('benchmark1.csv', header=True, index_label='session_id')

In [134]:
!head benchmark1.csv

session_id,target
1,0.005024876190096779
2,1.8210992335050216e-09
3,5.173946789984104e-11
4,7.012348831333823e-09
5,2.8990638894285236e-05
6,0.00015726766855237822
7,0.0006041072255553579
8,0.00010304508782212543
9,0.001673318248807253

In [135]:
new_feat_train = pd.DataFrame(index=train_df.index)
new_feat_test = pd.DataFrame(index=test_df.index)

In [136]:
new_feat_train['year_month'] = train_df['time1'].apply(lambda ts: 100 * ts.year + ts.month)
new_feat_test['year_month'] = train_df['time1'].apply(lambda ts: 100 * ts.year + ts.month)

In [137]:
new_feat_train.head()

            year_month
session_id
21669           201301
54843           201301
77292           201301
114021          201301
146670          201301

In [138]:
scaler = StandardScaler()
scaler.fit(new_feat_train[['year_month']])

new_feat_train['year_month_scaled'] = scaler.transform(new_feat_train[['year_month']])
new_feat_test['year_month_scaled'] = scaler.transform(new_feat_test[['year_month']])

In [139]:
new_feat_train.head()

            year_month  year_month_scaled
session_id
21669           201301          -1.744405
54843           201301          -1.744405
77292           201301          -1.744405
114021          201301          -1.744405
146670          201301          -1.744405

In [141]:
X_train_sparse_new = csr_matrix(hstack([X_train_sparse, new_feat_train['year_month_scaled'].values.reshape(-1, 1)]))
get_auc_1r_valid(X_train_sparse_new, y_train)

0.9145000295869065